name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  build_runner: ^2.4.15
  source_gen: ^2.0.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  boing_data_dpa:
    path: ../
  bcrypt: ^1.1.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
