name: boing_data_dpa
description: Boing Data DPA is a Dart/Flutter package inspired by Spring Data JPA, offering simplified data persistence using annotations. It supports SQLite, PostgreSQL, and MySQL databases.
version: 0.0.1
homepage: https://github.com/evandersondev/boing_data_dpa

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  yaml: ^3.1.3
  sqlite3: ^2.7.3
  postgres: ^3.5.1
  path: ^1.9.1
  source_gen: ^2.0.0
  analyzer: ^7.3.0
  uuid: ^4.5.1
  build: ^2.4.2
  glob: ^2.1.3
  cuid2: ^3.1.0
  mysql1: ^0.20.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
